# Generated by Django 4.2 on 2023-08-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
